FROM nginx:alpine

RUN apk add --no-cache iptables
RUN apk add --no-cache sudo

# Remove the default nginx index.html
RUN rm -rf /usr/share/nginx/html/index.html

# Copy the contents of the dist directory over to the nginx web root
COPY ./build/ /var/www/html/
COPY ./build/ /usr/share/nginx/html/

# Expose the public http port
EXPOSE 80

# Start server
CMD ["nginx", "-g", "daemon off;"]
